### ISSUE TITLE
[BUG] circular dependency error of vite

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geohub#4610]
### Bug Description

Sometimes, terminal shows the vite error for circular dependency

```
Error: [vite] The dependency module is not yet fully initialized due to circular dependency. This is a bug in Vite SSR
    at ssrImport (file:///Users/j_igarashi/Documents/git/UNDP-Data/geohub/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52922:19)
    at eval (/Users/j_igarashi/Documents/git/UNDP-Data/geohub/packages/svelte-undp-components/dist/components/ui/Breadcrumbs.svelte:4:37)
    at async instantiateModule (file:///Users/j_igarashi/Documents/git/UNDP-Data/geohub/node_modules/.pnpm/vite@5.4.11_@types+node@22.10.1_sass@1.81.0/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5)

```

but this is only problem in local, it works without any issues in production

### Bug Reproduction

- run `pnpm dev`
- run `make build` in different terminal
- error of circular dependency is shown sometimes

### Bug System Information

- OS: [e.g. Windows 10]
- Browser: [e.g. Google Chrome, Firefox]

**Comment by JinIgarashi** [comment]
let me close it for now
